# Generated by Django 5.0.7 on 2024-08-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='UserPosted',
        ),
        migrations.RenameField(
            model_name='userposted',
            old_name='name',
            new_name='username',
        ),
        migrations.CreateModel(
            name='RecipeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeTitle', models.CharField(max_length=200)),
                ('recipeDescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
