# Generated by Django 5.0.7 on 2024-08-28 20:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_author_userposted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedescription',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RenameField(
            model_name='recipedescription',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.AddField(
            model_name='recipedescription',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recipedescription',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipedescription',
            name='last_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
