# Generated by Django 5.0.7 on 2024-08-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_recipedescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedescription',
            name='postedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
